### PR TITLE
Fixed issue with enabling and disabling the addon

### PR DESCRIPTION
**Pull request by Szero**
Hello, I fixed issue referenced [here](https://chrome.google.com/webstore/detail/disable-download-bar/epnnapjdpplekmodajomjojfpeicclep/reviews?hl=en) by Timo Palomaa. Just added listeners on enable/disable events so extension doesn't ends up in off state.

### CODE REVIEW

**Comment by ivan7237d** [comment]
Thanks vm for the pull request! It's something that I'd really like fixed and I was going to merge it, but I experimented on one of my other extensions to see what happens when the "management" permission gets added, and it produces the following warning once the update comes in from the Web Store:

screen shot 2017-03-18 at 1 35 07 pm

It looks like an oversight in the Chrome API if the only way for an extension to track its own status is to get permission to manage all extensions — or is there another way? If not, then keeping things as they are would probably be the lesser of the two evils.

**Comment by Szero** [comment]
Yeah, It requires extra privileges to control state of an extension.
Also I thought I could add event listener on extension's enable button
in chrome://extensions page but it would require extra permissions anyways.

**Comment by ivan7237d** [comment]
Ok, let me close this for now, naturally feel free to publish the changes as a new extension. Thanks for having a go at it.

**Comment by silverbacknet** [comment]
Worth noting that this wouldn't work even with the extra permissions: The events only fire for other extensions. An Enable/Disable hook has been requested for ages, but so far isn't present.

**Comment by Jcee** [comment]
Extremely useful extension for those of us who download pictures :) heres a few Ideas/bugs
(minor bug) Doesn't work with canceled downloads. 
(bug) when downloading multiple files; It will close X seconds after any download completes. (it should be after the LAST download completes)
(suggestion) 'Insta-hide' a checkbox in the settings that makes it instantly hide the downloads bar, EVEN when downloads are active. Some people would prefer just to use ctrl+J to view the downloads page anyways :)

**Pull request closed without merging**
